title : NLJB - 别问我为啥叫加贝(哥名里有贺)
tagline: 别问我为啥叫加贝(哥名里有贺)
author :
  name : nljb
  email : nljb@nljb.net
  github : https://github.com/nulijiabei

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
